"""add sale_price_discounted and change sale_price to integer

Revision ID: 2ed133f5116c
Revises: 736c95441d70
Create Date: 2026-06-23 17:41:36.728555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ed133f5116c'
down_revision: Union[str, None] = '736c95441d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('sale_price_discounted', sa.Numeric(precision=12, scale=0), nullable=True))
    op.alter_column('properties', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'sale_price',
               existing_type=sa.Numeric(precision=12, scale=0),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.drop_column('properties', 'sale_price_discounted')
    # ### end Alembic commands ###
