"""initial tables

Revision ID: 736c95441d70
Revises: 
Create Date: 2026-06-20 13:54:59.166076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736c95441d70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('rental', 'sale', name='property_kind'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='property_status'), server_default='draft', nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_kind'), 'properties', ['kind'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'superadmin', name='user_role'), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('amenity_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amenity_id', 'locale', name='uq_amenity_locale')
    )
    op.create_index(op.f('ix_amenity_translations_amenity_id'), 'amenity_translations', ['amenity_id'], unique=False)
    op.create_table('property_amenities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('amenity_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'amenity_id', name='uq_property_amenity')
    )
    op.create_index(op.f('ix_property_amenities_amenity_id'), 'property_amenities', ['amenity_id'], unique=False)
    op.create_index(op.f('ix_property_amenities_property_id'), 'property_amenities', ['property_id'], unique=False)
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('public_id', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_images_property_id'), 'property_images', ['property_id'], unique=False)
    op.create_table('property_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locale', 'slug', name='uq_locale_slug'),
    sa.UniqueConstraint('property_id', 'locale', name='uq_property_locale')
    )
    op.create_index(op.f('ix_property_translations_locale'), 'property_translations', ['locale'], unique=False)
    op.create_index(op.f('ix_property_translations_property_id'), 'property_translations', ['property_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_translations_property_id'), table_name='property_translations')
    op.drop_index(op.f('ix_property_translations_locale'), table_name='property_translations')
    op.drop_table('property_translations')
    op.drop_index(op.f('ix_property_images_property_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_property_amenities_property_id'), table_name='property_amenities')
    op.drop_index(op.f('ix_property_amenities_amenity_id'), table_name='property_amenities')
    op.drop_table('property_amenities')
    op.drop_index(op.f('ix_amenity_translations_amenity_id'), table_name='amenity_translations')
    op.drop_table('amenity_translations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_kind'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('amenities')
    # ### end Alembic commands ###
