"""add locations table and replace property location with FK

Revision ID: 90a2cadb8941
Revises: 2ed133f5116c
Create Date: 2026-06-23 19:00:12.852116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90a2cadb8941'
down_revision: Union[str, None] = '2ed133f5116c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_table('location_translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'locale', name='uq_location_locale')
    )
    op.create_index(op.f('ix_location_translations_location_id'), 'location_translations', ['location_id'], unique=False)
    op.add_column('properties', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_properties_location_id'), 'properties', ['location_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.drop_column('properties', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_location_id'), table_name='properties')
    op.drop_column('properties', 'location_id')
    op.drop_index(op.f('ix_location_translations_location_id'), table_name='location_translations')
    op.drop_table('location_translations')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
